name: .NET Core

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

env:
  SOLUTION_PATH: "src/Trakx.Fireblocks.ApiClient.sln"
  FireblocksApiConfiguration__ApiPubKey: ${{secrets.FIREBLOCKS_API_KEY}}
  FireblocksApiConfiguration__ApiPrivateKey: ${{secrets.FIREBLOCKS_API_SECRET}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Add github nuget source
      run: dotnet nuget add source "https://nuget.pkg.github.com/trakx/index.json" --name "github" --username "trakx-bot" --password ${{secrets.TRAKX_BOT_READONLY_PAT}} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}

    - name: Remove github source
      run: dotnet nuget remove source "github"

    - name: Build
      run: |
        dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
        dotnet build ${{env.SOLUTION_PATH}} --configuration Debug --no-restore

    - name: Test & Coverage
      run: |
        for f in ./src/*.Tests/*.Tests.csproj; do echo "testing project $f" && \
        dotnet test $f --configuration Debug --no-restore --logger GitHubActions --verbosity normal\
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:UserSourceLink=true \
            /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\" \
            /p:Include=\"[Trakx.*]*\"; \
        done
        #dotnet test ${{env.SOLUTION_PATH}} --no-restore --logger GitHubActions --verbosity normal
    - name: Publish Coverage
      env:
        CODACY_PROJECT_TOKEN: ${{secrets.CODACY_TOKEN}}
      run: |
        for f in ./src/*.Tests/coverage.opencover.xml; do echo "sending coverage report $f" && \
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l csharp -r $f --partial --commit-uuid ${{github.sha}}; \
        done
        bash <(curl -Ls https://coverage.codacy.com/get.sh) final --commit-uuid ${{github.sha}}
